[build]
  base = "."
  publish = "build"

[[redirects]]
  from = "/service-worker.js*" 
  to = "/service-worker.js"
  status = 200
  headers = { cache-control = "max-age=0" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200